version: '1.0'

services:
  # falta definir los volumnes para la base de datos
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: root
      POSTGRES_DB: project-database
    ports:
      - 5432:5432
    networks:
      - express-app

  auth-backend-app:
    build:
      context: .
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://root:mysecretpassword@db/project-database
    networks:
      - express-app

networks:
  express-app:
