services:

  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=root
      - POSTGRES_DB=project-database
    ports:
      - 5432:5432
    networks:
      - toler-express-apps

  auth-backend-app:
    build:
      context: .
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - postgres-db
    environment:
      # examples
      - DATABASE_URL=postgres://root:mysecretpassword@postgres-db/project-database
      # cambiar / borrar token
      - JWT_SECRET="kjghiwu8673t439847vn><72"(vgSJa7><)"
    privileged: true
    networks:
      - toler-express-apps

networks:
  toler-express-apps:
    external: true
